# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# TODO delete this key once AWS understood
default: &DEFAULT
  eventbrite_key: N74NGC75C2SLVT3WM3
  eventbrite_secret: AEJZN2OB6VZE67GZPITIKVZTF5LLLUVFO3HTU4RA7MEV4JHYU7
  aws_key_id: AKIAI6K5KYZXC32QXTRA
  aws_secret: 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
  jwt_hmac_key: f5161040c2385e7f8ddb45cfbebce8f47e8d8a34043a69d5747e67f4539c93ad6cc62d3effcca87a490151e4640e593b333d009650bf33e175e932c2ce6b2ff6
  google_api_key: AIzaSyBFN4lQmn6IJWE-ynzilPVl6u6_67fPpg4
  soundcloud:
    id: 110f0efe017022a40d4629d8d660cdf1
    secret: 66740e63a06076e444b2ed7292875a2a
  yelp:
    consumer_key: qAl0zMCeUnc4c4OLBVyWNg
    consumer_secret: AJPudb8hgM1FuuXtFyNPifCjpUE
    token: lP5c-RUO2Axn-I2Uqrc19adLfU-uPwGW
    token_secret: mg8FJ4cMpCzurIRAZzjYhUwzfKk


development:
  secret_key_base: 481bb0051ac892b35445f9153b8310b6c127e006d6c494c9d09d6e8f2a258a5887f73bd60684858d3b9904f900b84b122f17e5fc3cffd02517ae5d3fffb7d41b
  facebook_app_id: 842337999153841
  facebook_secret: 569134af954600ae1214cb8573ff3566
  <<: *DEFAULT

test:
  secret_key_base: 0af25ed6a3305f387d0ddfcf8ecee1bd54adfb9ac08fca9b5d28e94a31e681664de30f2ef8c8dbb59130f7ec5ad1aec3b575e35d05132acec07f81c4e8d82a80
  <<: *DEFAULT

staging:
  <<: *DEFAULT
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 915436455177328
  facebook_secret: 103d2edb785a4653380d191f9a50c1a4
  facebook_callback_secret: EaQnhae7HoTbfc3z4vJ0vcWlwV3rRup/XtNgfX9OWVA=
  soundcloud:
    id: 110f0efe017022a40d4629d8d660cdf1
    secret: 66740e63a06076e444b2ed7292875a2a
  yelp:
    consumer_key: qAl0zMCeUnc4c4OLBVyWNg
    consumer_secret: AJPudb8hgM1FuuXtFyNPifCjpUE
    token: lP5c-RUO2Axn-I2Uqrc19adLfU-uPwGW
    token_secret: mg8FJ4cMpCzurIRAZzjYhUwzfKk


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 713525445368431
  facebook_secret: 1e8e5221e2abf081cb86fdc0d9631024
  aws_key_id: AKIAI6K5KYZXC32QXTRA
  aws_secret: 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
  google_api_key: AIzaSyBFN4lQmn6IJWE-ynzilPVl6u6_67fPpg4
  facebook_callback_secret: <%= ENV["FACEBOOK_CALLBACK_SECRET"] %>
  soundcloud:
    id: 110f0efe017022a40d4629d8d660cdf1
    secret: 66740e63a06076e444b2ed7292875a2a
  yelp:
    consumer_key: qAl0zMCeUnc4c4OLBVyWNg
    consumer_secret: AJPudb8hgM1FuuXtFyNPifCjpUE
    token: lP5c-RUO2Axn-I2Uqrc19adLfU-uPwGW
    token_secret: mg8FJ4cMpCzurIRAZzjYhUwzfKk
