---
locales:
  - label: test
    name: Test
    beacon_major: 1
  - label: seattle
    name: Seattle
    google_place_id: ChIJVTPokywQkFQRmtVEaUZlJRA
    beacon_major: 2
    venues:
      - name: Purr
        facebook_id: 183716211669747
        google_place_id: ChIJZ7Txss1qkFQRVoA8fYl4Rx0
        beacon_minors:
          - 1
      - name: RPlace
        facebook_id: 58260309278
        google_place_id: ChIJ-aXMYctqkFQRR5sJuXK6b_I
      - name: Neighbors
        facebook_id: 505306519485467
        google_place_id: ChIJk_aBY8xqkFQRSZgw2100Z0o
      - name: CC Attles
        facebook_id: 111565388880689
        google_place_id: ChIJk-Ws_tFqkFQRc2h8MPRvv5I
      - name: Eagle
        facebook_id: 1276536252393237
        google_place_id: ChIJOcPt38pqkFQRWmTOs3bUrgk
      - name: The Cuff
        facebook_id: 113908521985880
        google_place_id: ChIJuQVbk81qkFQRkm6N_RnwHQY
      - name: Pony
        facebook_id: 196120291315
        google_place_id: ChIJRUOyfc5qkFQRDZLLFj1Q264
      - name: Madison Pub
        facebook_id: 276407207694
        google_place_id: ChIJB_-ecc5qkFQRS1xH4lgadrg
      - name: Crescent Lounge
        facebook_id: 123506914343456
        google_place_id: ChIJh-aSYTMVkFQRBC6htmNquI0
  - label: spokane
    name: Spokane
    google_place_id: ChIJ5ee7MFwYnlQRsdmEC9bJ_N0
    beacon_major: 3
    venues:
      - name: Stray
        facebook_id: 230964110609623
        google_place_id: ChIJoZ-XpGEYnlQRFn67pKW7sUs
        beacon_minors:
          - 2
          - 3
      - name: Nyne
        facebook_id: 208226991785
        google_place_id: ChIJjSkjDooYnlQRFGPhbtxVauk
        beacon_minors:
          - 1
  - label: nyc
    name: New York
    google_place_id: ChIJOwg_06VPwokRYv534QaPC8g
    beacon_major: 4
    venues:
      - name: Industry
        facebook_id: 129095523800790
        google_place_id: ChIJs5moEldYwokRUeku57R4FfA
        beacon_minors:
          - 2
      - name: The Ritz
        facebook_id: 114451068615283
        google_place_id: ChIJXRLW4VNYwokR86GtMXsa4KM
        beacon_minors:
          - 3
      - name: The Eagle (NYC)
        facebook_id: 128608363801
        google_place_id: ChIJmaM5RbZZwokRwpJUp-ClLKw
        beacon_minors:
          - 6
      - name: Boxers HK
        facebook_id: 377763576116
        google_place_id: ChIJ78MqK1dYwokRX8ecRYNZQDo
      - name: Boxers Chelsea
        facebook_id: 242947875741618
        google_place_id: ChIJ33p4aaNZwokRaqz6qL-Z_Rc
      - name: 9th Ave Saloon
        google_place_id: ChIJmeUU3FNYwokRb5-sS-RTfYU
        beacon_minors:
          - 4
      - name: Atlas Social Club
        facebook_id: 498962873531494
        google_place_id: ChIJSYrBMldYwokRuer87cJcwiw
      - name: Therapy
        facebook_id: 160485380671853
        google_place_id: ChIJ69_1EldYwokRRA5fa21Vu_8
      - name: Posh
        facebook_id: 101408476608233
        google_place_id: ChIJazo0y1BYwokRtxo_g27YBA0
      - name: Flaming Saddles
        facebook_id: 202780666453004
        google_place_id: ChIJ41LLW1dYwokR7Q5UGoWYbiE
        beacon_minors:
          - 5
      - name: Rise Bar
        facebook_id: 150826568602220
        google_place_id: ChIJqRRpsFlYwokRS2bmqrh0tzc
      - name: Townhouse of New York
        facebook_id: 111601412213573
        google_place_id: ChIJq2491OVYwokRJCKqoN3hZIY
      - name: Hardware
        facebook_id: 309080542468946
        google_place_id: ChIJaRE_uFFYwokRSgI8YRDfnDk
      - name: Baraccuda
        facebook_id: 144234300350
        google_place_id: ChIJg912rrtZwokRplCG3u0bCuo
      - name: Stonewall
        facebook_id: 108304452852860
        google_place_id: ChIJTQoVbZRZwokRx0ocj9EU2sA
      - name: Pieces
        facebook_id: 120872870793
        google_place_id: ChIJ_YhXopZZwokRAlsPWL2btI0
        beacon_minors:
          - 1
      - name: Rockbar
        facebook_id: 147920711697
        google_place_id: ChIJlwfqXuxZwokRTlizRW_4cwc
      - name: Nowhere
        facebook_id: 359021430802562
        google_place_id: ChIJZ1fMFZ5ZwokRkYrV85CZorY
      - name: The Cock
        facebook_id: 204660862919346
        google_place_id: ChIJQ8iS8YRZwokRBsrnhO_DFUQ
      - name: Duplex
        google_place_id: ChIJw-gIcpRZwokRz2K4g1SPOS4
        facebook_id: 130651285858
      - name: The Monster
        google_place_id: ChIJHUZodJRZwokR3Mdk_jks8Ss
        facebook_id: 197191882951
      - name: The Hanger
        google_place_id: ChIJi6U2WZNZwokRyt48I1048Io
      - name: Metropolitan
        google_place_id: ChIJ4T3ytllZwokR25u7NCunH-g
        facebook_id: 62349112474
      - name: Mickey Spillane's
        google_place_id: ChIJuz62MlFYwokRPxcI1Dqu3yE
        facebook_id: 314918441961441
      - name: Ty's Bar NYC
        google_place_id: ChIJaVvpXJNZwokRT3p02KL_TrY
      - name: Toolbox
        google_place_id: ChIJHf-KOKVYwokRfVh5IBt6Ng8
        facebook_id: 345797544053
      - name: Adonis Lounge
        google_place_id: ChIJLUJT0OVYwokRY9hE0xs1yKg
      - name: Suite
        google_place_id: ChIJ2zEbuzz2wokRTNeIjzlujUs
        facebook_id: 102820659801268
      - name: Uncle Charlie's
        google_place_id: ChIJf1hdhgJZwokRcrTxCK3u9Uw
        facebook_id: 111747135529421
      - name: Boiler Room
        google_place_id: ChIJAydFqYRZwokRo1s2sj0i4Rc
      - name: Barrage
        google_place_id: ChIJYVb4aFFYwokR3wuCopreEQc
        facebook_id: 606036202839690
      - name: Eastern Bloc
        google_place_id: ChIJBSuPrIJZwokRe80sRG6sRQU
        facebook_id: 479889198695842
      - name: Evolve
        google_place_id: ChIJVc4w0OVYwokRwmXAyAnF4vY
      - name: Icon Bar
        google_place_id: ChIJR2_C-DlfwokRUk2U_5UEQ5g
        facebook_id: 1375125006052293
      - name: Gym Sportsbar
        google_place_id: ChIJX-P_qr5ZwokR7pssvk2V9b0
        facebook_id: 49447833149
      - name: Albatross
        google_place_id: ChIJ8RSx_WlfwokRa_PTy_InEnM
        facebook_id: 812078902145676
      - name: Hombres
        google_place_id: ChIJAThTe69fwokRrTgTVE6FwoA
        facebook_id: 256407097735822
      - name: Friend's Tavern
        google_place_id: ChIJTQbElalfwokRPMz8RyVkf3k
        facebook_id: 143500412336402
      - name: Marie's Crisis Cafe
        google_place_id: ChIJIWNZgJNZwokRsOATqnluSIk
        facebook_id: 445984192133617
      - name: Club Evolution
        google_place_id: ChIJ4QV7_alfwokRd146wIFI3tU
        facebook_id: 192279067449000
      - name: Boots and Saddle
        google_place_id: ChIJN99VfpRZwokRA3AOcLoIcow
        facebook_id: 136385793129080
      - name: Phoenix Bar
        google_place_id: ChIJjcdLdHZZwokRAUBQoPz63oY
      - name: The Pyramid Club
        google_place_id: ChIJm2s9Tp1ZwokRwr15Gf7VcAs
        facebook_id: 113717645308349
      - name: Bedlam
        google_place_id: ChIJ-_cJ43hZwokRF5vAmhR6Jug
        facebook_id: 647857748677272
      - name: Cubbyhole
        google_place_id: ChIJAc17d5VZwokRFRZJneeCMww
        facebook_id: 58574429985
      - name: 11:11 Eleven Eleven
        google_place_id: ChIJtw_nS4JZwokRuhl1nSIzPTc
      - name: The Out Hotel
        google_place_id: ChIJc87lok1YwokRJzddYNyu9Ys
      - name: XL
        google_place_id: ChIJw_vbok1YwokR5jfP7CIE8PE
        facebook_id: 332809110145478
      - name: Henrietta Hudson
        google_place_id: ChIJhyhbK-1ZwokRmOnWy-LnDEc
        facebook_id: 100338230043140
      - name: Castro
        google_place_id: ChIJQ7dXIwb0wokR9GA9c_W3Hus
        facebook_id: 223873847792501
      - name: Brandy's Piano Bar
        google_place_id: ChIJ0d55irtYwokRL3L_psDROgY
        facebook_id: 279949132051489
      - name: The Abbey
        google_place_id: ChIJ-wN4MVxZwokRKoZI7m-lYGk
        facebook_id: 1397699750444792
      - name: The Woods
        google_place_id: ChIJNaaqo9hbwokRhf0e1A8UyYQ
        facebook_id: 107368579428597
      - name: Marquee New York
        google_place_id: ChIJBwnlGrdZwokRpf61pMm860c
        facebook_id: 114557118703771
      - name: Open House Club
        google_place_id: ChIJbwlMwYhZwokRyBqYrqVNdr0
        facebook_id: 145911425516995
      - name: Vodka Soda & Bottoms Up
        google_place_id: ChIJvb1EBlRYwokRnX52ll4OW4Q
        facebook_id: 1619167065076093
      - name: Bill's Gay Nineties
        google_place_id: ChIJ04HKFvtYwokR--dPQNsNhYE
  - label: denver
    name: Denver
    google_place_id: ChIJzxcfI6qAa4cR1jaKJ_j0jhE
    beacon_major: 5
  - label: boston
    name: Boston
    google_place_id: ChIJGzE9DS1l44kRoOhiASS_fHg
    beacon_major: 6
  - label: dc
    name: Washingtion DC
    google_place_id: ChIJW-T2Wt7Gt4kRKl2I1CJFUsI
    beacon_major: 7
  - label: sf
    name: San Francisco
    google_place_id: ChIJIQBpAG2ahYAR_6128GcTUEo
    beacon_major: 8
  - label: portland
    name: Portland
    google_place_id: ChIJJ3SpfQsLlVQRkYXR9ua5Nhw
    beacon_major: 9
  - label: austin
    name: Austin
    google_place_id: ChIJLwPMoJm1RIYRetVp1EtGm10
    beacon_major: 10
  - label: neworleans
    name: New Orleans
    google_place_id: ChIJZYIRslSkIIYRtNMiXuhbBts
    beacon_major: 11
  - label: slc
    name: Salt Lake
    google_place_id: ChIJ7THRiJQ9UocRyjFNSKC3U1s
    beacon_major: 12
  - label: hartford
    name: Hartford
    google_place_id: ChIJpVER8hFT5okRmVl96ahKjsw
    beacon_major: 13
  - label: la
    name: Los Angeles
    google_place_id: ChIJE9on3F3HwoAR9AhGJW_fL-I
    beacon_major: 14
  - label: louisville
    name: Louisville
    google_place_id: ChIJEdVbsxoLaYgRMv1xICi009Q
    beacon_major: 15
  - label: providence
    name: Providence
    google_place_id: ChIJXXN-Q-BE5IkRJ7azSE1832k
    beacon_major: 16
  - label: virginiabeach
    name: Virginia Beach
    google_place_id: ChIJpycV_OjBuokRcwEuo4AQFgQ
    beacon_major: 17
  - label: columbus
    name: Columbus
    google_place_id: ChIJcd6QucGJOIgRM7Wxz_hmMuQ
    beacon_major: 18
  - label: jacksonville
    name: Jacksonville
    google_place_id: ChIJ66_O8Ra35YgR4sf8ljh9zcQ
    beacon_major: 19
  - label: chicago
    name: Chicago
    google_place_id: ChIJ7cv00DwsDogRAMDACa2m4K8
    beacon_major: 20
  - label: sandiego
    name: San Diego
    google_place_id: ChIJSx6SrQ9T2YARed8V_f0hOg0
    bacon_major: 21