---
- id: 1
  name: Purr
  locale_id: 2
- id: 2
  name: RPlace
  locale_id: 2
- id: 3
  name: Neighbors
  locale_id: 2
- id: 4
  name: CC Attles
  locale_id: 2
- id: 5
  name: Eagle
  locale_id: 2
- id: 6
  name: The Cuff
  locale_id: 2
- id: 7
  name: Pony
  locale_id: 2
- id: 8
  name: Madison Pub
  locale_id: 2
- id: 9
  name: Crescent Lounge
  locale_id: 2
- id: 10
  name: Stray
  locale_id: 3
  facebook_id: 230964110609623
  beacons:
    - 1
    - 2
    - 3
- id: 11
  name: Nyne
  locale_id: 3
  facebook_id: 208226991785
  beacons:
    - 4
    - 5
    - 6
